// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqoNf3s3OXAJKo0S2cYJxmzSwARtn7kE',
    appId: '1:461282352329:android:cabf6167b02087068f8118',
    messagingSenderId: '461282352329',
    projectId: 'ckcsocial-6c1e8',
    storageBucket: 'ckcsocial-6c1e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoM-UCJlNxOfQFe1f581hPXdsU3NlmT7Y',
    appId: '1:461282352329:ios:f2ff2821763d80548f8118',
    messagingSenderId: '461282352329',
    projectId: 'ckcsocial-6c1e8',
    storageBucket: 'ckcsocial-6c1e8.appspot.com',
    iosClientId: '461282352329-3nuhbr3n2q89k5qa2i0a96clgvpo5ejm.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoM-UCJlNxOfQFe1f581hPXdsU3NlmT7Y',
    appId: '1:461282352329:ios:f2ff2821763d80548f8118',
    messagingSenderId: '461282352329',
    projectId: 'ckcsocial-6c1e8',
    storageBucket: 'ckcsocial-6c1e8.appspot.com',
    iosClientId: '461282352329-3nuhbr3n2q89k5qa2i0a96clgvpo5ejm.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
